AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'QA on AWS - Simple PDF processing with Step Functions'

Parameters:
  Environment:
    Type: String
    Default: dev
    Description: Environment name

Resources:
  # S3 Bucket (usando bucket existente)
  # Como o bucket já existe, vamos apenas referenciar

  # Lambda Function
  ProcessPDFFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'qa-on-aws-${Environment}-process-pdf'
      CodeUri: lambdas/
      Handler: process_pdf.lambda_handler
      Runtime: python3.11
      Timeout: 60
      Environment:
        Variables:
          BUCKET_NAME: source-pdf-qa-aws
      Policies:
        - S3ReadPolicy:
            BucketName: source-pdf-qa-aws

  # Step Functions State Machine
  ProcessingStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: !Sub 'qa-on-aws-${Environment}-processing'
      DefinitionUri: state_machines/processing.json
      DefinitionSubstitutions:
        ProcessPDFFunctionArn: !GetAtt ProcessPDFFunction.Arn
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref ProcessPDFFunction

Outputs:
  BucketName:
    Value: source-pdf-qa-aws
  StateMachineArn:
    Value: !Ref ProcessingStateMachine
  LambdaFunctionArn:
    Value: !GetAtt ProcessPDFFunction.Arn